name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  dio: ^5.8.0+1
  flutter_hooks: ^0.20.5
  connectivity_plus: ^6.1.3
  auth:
    path: ../
  di:
    git:
      url: https://github.com/quochoang228/di.git
      ref: main
  router:
    git:
      url: https://github.com/quochoang228/router.git
      ref: main
  ag:
    git:
      url: https://github.com/quochoang228/ag.git
      ref: main
  storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: storage
      ref: main

  persistent_storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: persistent_storage
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  auth:
      path: ../

flutter:
  uses-material-design: true
